### ISSUE TITLE
kube-secrets-init not working on kubernetes 1.18.12

### ISSUE THREAD

**Issue by Loyalsys-Ori** [doitintl/kube-secrets-init#13]
admissionregistration.k8s.io/v1beta1 is not available anymore and now we need to use admissionregistration.k8s.io/v1 
I tried to change it manually but got errors like : 
"Internal error occurred: failed calling webhook "secrets-init.doit-intl.com": Post https://secrets-init-webhook-svc.default.svc:443/pods?timeout=30s: context deadline exceeded"

**Comment by rustysys-dev** [comment]
@alexei-led @Loyalsys-Ori 

Is this still relevent? It seems like there was a commit that addressed the deprecated API version, but that was around the same time as this issue.  I was wondering if this has been fixed already?

**Comment by alexei-led** [comment]
fixed supporting admissionregistration.k8s.io/v1 now

**Comment by Loyalsys-Ori** [comment]
Thanks, I will check it soon!
