### ISSUE TITLE
Failed to resolve secrets with enabled workload identity

### ISSUE THREAD

**Issue by mkryva** [doitintl/kube-secrets-init#2]
Hi! I've enabled workload identity and link GSA and K8S_SA of services. But receive this error:

`time=“2020-04-16T21:22:10Z” level=error msg=“failed to resolve secrets” error=“failed to get secret from Google Secret Manager: rpc error: code = Unauthenticated desc = transport: Get \“http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token?scopes=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform\“: net/http: timeout awaiting response headers”
`

**Comment by alexei-led** [comment]
@mkryva please try again, probably this due gcloud SDK timeout issue. I've added a fallback/retry logic.

**Comment by mkryva** [comment]
Can you provide commit on fix?

**Comment by gordonbondon** [comment]
Seems to be related to doitintl/secrets-init#3
