### ISSUE TITLE
Support for private aws ecr registries

### ISSUE THREAD

**Issue by awasilyev** [doitintl/kube-secrets-init#24]
Currently it is fails if image for container is from private aws ecr registry:
```
2021/07/13 15:18:36 registry.ping url=https://857306286857.dkr.ecr.eu-west-1.amazonaws.com/v2/
```

**Comment by zenyui** [comment]
@awasilyev I think you're having the same issue we had in GCP, see my workaround here: https://github.com/doitintl/kube-secrets-init/issues/22#issuecomment-987611520
