### ISSUE TITLE
Replace for the secretKeyRef doesn't work

### ISSUE THREAD

**Issue by DmytroRybka** [doitintl/kube-secrets-init#29]
Hi,

When I look into the code I see that it should be possible to use the "placeholder" for  **SecretKeyRef**  but  when I use it I'm getting the validation error 
`is invalid: spec.template.spec.containers[0].env[6].valueFrom.secretKeyRef.key: Invalid value:   a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-.
_a-zA-Z0-9]+')
`

- name: kafka_api_key
    valueFrom:
      secretKeyRef:
        name: myservice
        key: gcp:secretmanager:projects/111222666333/secrets/kafkaKey

![image](https://user-images.githubusercontent.com/437951/151407052-6a728f43-40d4-4dac-bf63-b7dbda1a24a3.png)

**Comment by alexei-led** [comment]
The `secretKeyRef` should point to K8s secret and then the value of this secret can be substituted by the secrets-init webhook
