### ISSUE TITLE
Add support for v1 AdmissionReview

### ISSUE THREAD

**Issue by sagikazarmark** [doitintl/kube-secrets-init#4]
FYI I opened an issue in the upstream webhook repo to add support for this: https://github.com/slok/kubewebhook/issues/72

**Comment by alexei-led** [comment]
fixed with 0.2.15

**Comment by sagikazarmark** [comment]
@alexei-led unfortunately, that's not enough. Please see the issue I linked.

**Comment by alexei-led** [comment]
@sagikazarmark indeed, reopening the issue

**Comment by alexei-led** [comment]
update to kubewebhook v2 once released (beta now)

**Comment by sagikazarmark** [comment]
Maybe update and release a beta as well? I think the author is waiting for some feedback: https://github.com/slok/kubewebhook/issues/72#issuecomment-765198546

**Comment by sagikazarmark** [comment]
Looks like v2 is released.
