### ISSUE TITLE
Support for Oracle Cloud Vault

### ISSUE THREAD

**Issue by herberthnilsen** [doitintl/kube-secrets-init#43]
Hi,

I work at Oracle and a customer is using this component, I clone your repo and make an update to support Oracle Cloud Vault

please, check it out and when possible include this directly on your repo.

I don't know Go Lang, so I don't create the files to test the solution and I comment a lot of lint that was on Makefile just to build the container, 

The solution is working to Oracle Cloud Vault, but don't have automated test files.

Checkout on my git

https://github.com/herberthnilsen/secrets-init
https://github.com/herberthnilsen/kube-secrets-init

**Comment by alexei-led** [comment]
I have no plans to support Oracle cloud, but can review the PR (with tests and docs)

**Comment by herberthnilsen** [comment]
I'll create a PR and improving the docs about OCI, but without tests, like a said, I don't know GoLang and I'm unable to create the test files.

This solution to OCI is running today on the greatest retail company in Brazil, so it works fine, but I don't know Go and I won't make the test files.

that's it, thanks for your time

Be fine
