### ISSUE TITLE
Publish images on ghcr.io

### ISSUE THREAD

**Issue by sagikazarmark** [doitintl/kube-secrets-init#5]
As of November, Docker Hub will enforce radical [rate limiting policies](https://www.docker.com/pricing/resource-consumption-updates) which affects basically the whole world.

As a response to that change, GitHub introduced a new [image registry](https://github.blog/2020-09-01-introducing-github-container-registry/).

Many projects are migrating away from Docker Hub, because the 100 pulls/IP/6 hours is hitting Kubernetes users hard (especially with private clusters).

It would be nice to have images pushed to ghcr.io as well. I'd be happy to provide a PR to your GitHub Actions workflows.

**Comment by alexei-led** [comment]
done https://github.com/orgs/doitintl/packages/container/package/kube-secrets-init

**Comment by sagikazarmark** [comment]
Awesome, thanks!
